### ISSUE TITLE
4K Cameras – Write the YARP driver

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/study-icub-head#14]
We're required to expose the video stream acquired from the cameras to YARP.
The stream should be already accessible through `udev`.

**Comment by triccyx** [comment]
@pattacini @Nicogene 
A final note, on the last test done on Friday the 14th during the demo:
- Max available resolution 4190x3120 
- The Basler sensor has a native factor of 4/3. It seems that the camera solves resolutions, with a different factor, with a hidden crop (the pencil test done with @S-Dafarra ).
- Testing with 1440x1600, that is the visor resolution the fps=27/28 with two cams

cc: @S-Dafarra
