### ISSUE TITLE
Integrate documentation for the models

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/study-icub-head#32]
Aside from the [missing documentation](https://github.com/icub-tech-iit/study-icub-head/issues/2#issuecomment-1248171485) that we need to push, my feeling is that it's a bit obscure what's happening underneath when we launch the scripts and/or simulate the models. Maybe a Live Script can help here.

_Originally posted by @pattacini in https://github.com/icub-tech-iit/study-icub-head/issues/2#issuecomment-1272949110_

**Comment by mfussi66** [comment]
Started documenting the work through a live script, here is a preview:


https://user-images.githubusercontent.com/38140169/214078956-7de63a79-9ea3-4923-8990-7297de87769d.mp4

Maybe it could be useful to reduce the verbosity of commands and plot the full fledged simulation results in the end?

**Comment by pattacini** [comment]
Super!

>Maybe it could be useful to reduce the verbosity of commands and plot the full fledged simulation results in the end?


Let's keep it as it is for now.
