### ISSUE TITLE
4K Cameras – Modifications needed

### ISSUE THREAD

**Issue by salvi-mattia** [icub-tech-iit/study-icub-head#33]
here's a list of modifications for the head after the test on icub3
- [ ] holes for traco in frame's "nose"
- [ ] better allocation for basler adapters
- [ ] make a decision about eyelids
- [ ] define comexpress mounting angle -> heatsink opening

**Comment by pattacini** [comment]
Great @salvi-mattia 👍🏻 
Can we close #26 then?

**Comment by pattacini** [comment]
I've closed the issue #26 as all the outstanding points have been ported here.
