### ISSUE TITLE
Test WiFi on both COM-EXP and Xavier

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/study-icub-head#34]
With regards to the new iCub Head (UKIT009), we're required to evaluate the following configuration:
- WiFi enabled on COM-EXP.
- WiFi enabled on Xavier NX (there's a new antenna with a 90-deg connector).
- Two Basler cameras streaming data at the given resolution and rate. 
- The two WiFi antennas kept 10 cm apart.
- The COM-EXP doing something on the WiFi (to try to bother the Xavier).

cc @S-Dafarra @DanielePucci @maggia80

**Comment by Nicogene** [comment]
Alongside @davidelasagna we tested the new network configuration with the two wifi antennas.

In this configuration, the Xavier NX is connected to the wifi with the IP `10.0.0.5`, the com-express has the usual `10.0.0.2`.

We put the antennas of the two boards one over the other and we made stream the images from the Xavier NX, and we made the com-express ping at high frequency the server (`10.0.0.1`) with this command:

``` bash
sudo ping -i 0.01 -s 65507 10.0.0.1
```

here are the results of the glass to glass

# 1440x1600

![immagine](https://user-images.githubusercontent.com/19152494/198240054-cf3d4280-dafd-492e-9ec3-a8318adb86e0.png)


# 1080x1920

![immagine](https://user-images.githubusercontent.com/19152494/198240324-5f91ca4e-7344-4f66-aa40-08fd415cca16.png)


cc @pattacini @maggia80 @S-Dafarra @DanielePucci

**Comment by pattacini** [comment]
Super!

**Comment by S-Dafarra** [comment]
The reference performance was in https://github.com/icub-tech-iit/study-icub-head/issues/30#issuecomment-1270102582 with the image (I am not sure we put it in any other comment)
![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/18591940/198242231-52290fe1-09ab-4d9d-b082-e27bdc2e4c3f.png)

The latency there was ~160ms, so they are comparable I would say

**Comment by Nicogene** [comment]
Just a note, this result (https://github.com/icub-tech-iit/study-icub-head/issues/34#issuecomment-1293219647) was using `1080x1920`

**Comment by DanielePucci** [comment]
Very nice guys, definitively a solution to consider
